---
- name: Add yum repository for docker
  ansible.builtin.template:
    src: docker-ce.repo.j2
    dest: /etc/yum.repos.d/docker-ce.repo
    owner: root
    group: root
    mode: "0644"

- name: Install required packages for docker
  ansible.builtin.dnf:
    name: "{{ item }}"
  loop: "{{ packages }}"

- name: Enable and start docker service
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started

# docker install from https://github.com/adamvlasak/ansible-rockylinux/tree/master

- name: Ensure pip is installed
  ansible.builtin.dnf:
    name: python3-pip
    state: present

- name: Install required Python packages
  ansible.builtin.pip:
    name:
      - packaging
      - requests==2.31.0
      - docker
    executable: /usr/bin/pip3
    state: present
# from debugging with chatgpt

- name: Install Docker Compose
  ansible.builtin.pip:
    name: docker-compose
    executable: /usr/bin/pip3
    state: present
